jenkinsci/pull-request-monitoring-plugin

- .github/workflows/coverage.yml
- Jenkinsfile
- README.md
- pom.xml
- src/test/java/io/jenkins/plugins/monitoring/MonitorTest.java
> first unit test

- etc/Jenkinsfile.custom
- etc/Jenkinsfile.default
- pom.xml
> Add demo Jenkinsfiles

- src/main/resources/io/jenkins/plugins/monitoring/MonitoringBuildAction/index.jelly
> Show plugin title instead of id in the dropdown list of 'Add item' modal

- src/main/java/io/jenkins/plugins/monitoring/MonitorView.java
> Add default implementation for view id in the MonitorView interface

- README.md
> add live demo from ux sig meeting to README.md

- src/main/webapp/css/pull-request-monitoring.css
- src/main/webapp/js/pull-request-monitoring.js
> rework of slot sizes inside the dashboard (1 to 5), 1 unit equals 150px

- src/main/java/io/jenkins/plugins/monitoring/MonitoringMultibranchProjectAction.java
- src/main/java/io/jenkins/plugins/monitoring/MonitoringWorkflowJobActionFactory.java
> SCMChangeRequest discovery via SCMHead-Class instead of branch-pronoun

- pom.xml
- src/main/java/io/jenkins/plugins/monitoring/MonitorUserProperty.java
- src/main/java/io/jenkins/plugins/monitoring/MonitoringBuildAction.java
- src/main/resources/io/jenkins/plugins/monitoring/MonitoringBuildAction/index.jelly
- src/main/webapp/js/pull-request-monitoring.js
> simplified/rework configuration persistence (MonitorUserProperty)

- pom.xml
> Bump muuri-api from 0.9.3-1 to 0.9.3-2, change jenkins baseline to 2.249.x

- pom.xml
> remove unused dependencies (font-awesome-api & plugin-util-api)

- src/main/java/io/jenkins/plugins/monitoring/MonitorView.java
- src/main/resources/io/jenkins/plugins/monitoring/ExampleMonitor/monitor.jelly
- src/main/resources/io/jenkins/plugins/monitoring/MonitoringBuildAction/index.jelly
- src/main/webapp/css/pull-request-monitoring.css
> add detailViewUrl as new method to MonitorView interface

- src/main/java/io/jenkins/plugins/monitoring/MonitorView.java
- src/main/resources/io/jenkins/plugins/monitoring/ExampleMonitor/monitor.jelly
> add icon url to MonitorView interface

- pom.xml
- src/main/resources/io/jenkins/plugins/monitoring/MonitoringMultibranchProjectAction/index.jelly
> update from bootstrap4 to bootstrap5

- pom.xml
- src/main/resources/io/jenkins/plugins/monitoring/MonitoringBuildAction/index.jelly
- src/main/webapp/css/pull-request-monitoring.css
- src/main/webapp/js/pull-request-monitoring.js
> use color-picker instead static color selection (black, green, red, blue)

- src/main/java/io/jenkins/plugins/monitoring/Monitor.java
- src/main/java/io/jenkins/plugins/monitoring/MonitorUserProperty.java
- src/main/java/io/jenkins/plugins/monitoring/MonitorView.java
- src/main/java/io/jenkins/plugins/monitoring/MonitoringBuildAction.java
- src/main/resources/io/jenkins/plugins/monitoring/MonitoringBuildAction/index.jelly
- src/main/resources/io/jenkins/plugins/monitoring/MonitoringBuildAction/index_de_DE.properties
- src/main/resources/io/jenkins/plugins/monitoring/MonitoringBuildAction/index_en_US.properties
- src/main/webapp/css/pull-request-monitoring.css
- src/main/webapp/js/pull-request-monitoring.js
- src/test/java/io/jenkins/plugins/monitoring/MonitorTest.java
> add preferredWidth and preferredHeight to MonitorView interface

- src/main/java/io/jenkins/plugins/monitoring/MonitoringBuildAction.java
- src/main/resources/io/jenkins/plugins/monitoring/MonitoringBuildAction/index.jelly
> add alert if unavailable monitors are used in user configuration

- src/main/java/io/jenkins/plugins/monitoring/Monitor.java
- src/main/java/io/jenkins/plugins/monitoring/MonitorPortlet.java
- src/main/java/io/jenkins/plugins/monitoring/MonitorPortletFactory.java
- src/main/java/io/jenkins/plugins/monitoring/MonitoringBuildAction.java
- src/main/resources/alerts/warning.jelly
- src/main/resources/alerts/warning_de_DE.properties
- src/main/resources/alerts/warning_en_US.properties
- src/main/resources/io/jenkins/plugins/monitoring/MonitoringBuildAction/index.jelly
- src/main/resources/modals/add-portlet.jelly
- src/main/resources/modals/add-portlet_de_DE.properties
- src/main/resources/modals/add-portlet_en_US.properties
- src/main/resources/modals/config.jelly
- src/main/resources/modals/config_de_DE.properties
- src/main/resources/modals/config_en_US.properties
- src/main/resources/portlet/portlet.jelly
- src/main/webapp/js/pull-request-monitoring.js
> outsource parts of build action jelly file

- src/main/java/io/jenkins/plugins/monitoring/Monitor.java
- src/main/java/io/jenkins/plugins/monitoring/MonitorPortletFactory.java
- src/main/resources/io/jenkins/plugins/monitoring/MonitoringBuildAction/index.jelly
- src/main/resources/modals/add-portlet.jelly
- src/main/resources/modals/add-portlet_de_DE.properties
- src/main/resources/modals/add-portlet_en_US.properties
> add <optgroup> to dropwdown list (factory names)

- .github/auto_assign.yml
- .github/workflows/assign-pr.yml
- pom.xml
- src/main/java/io/jenkins/plugins/monitoring/ExamplePortlet.java
- src/main/resources/io/jenkins/plugins/monitoring/ExamplePortlet/monitor.jelly
- src/test/java/io/jenkins/plugins/monitoring/MonitorTest.java
> implement demo portlet for release

- src/main/java/io/jenkins/plugins/monitoring/MonitorPortletFactory.java
> change access from private to public for MonitorPortletFactory

- src/main/webapp/js/pull-request-monitoring.js
> fix wrong visibility of inputs after configuration reset

- src/main/resources/io/jenkins/plugins/monitoring/MonitoringMultibranchProjectAction/index.jelly
> fix wrong action url for pull request overview items

- README.md
- src/main/java/io/jenkins/plugins/monitoring/MonitoringDefaultAction.java
- src/main/java/io/jenkins/plugins/monitoring/MonitoringMultibranchProjectAction.java
- src/main/java/io/jenkins/plugins/monitoring/MonitoringWorkflowJobAction.java
- src/main/java/io/jenkins/plugins/monitoring/MonitoringWorkflowJobActionFactory.java
> actions will not be displayed if user is not logged in

- src/main/java/io/jenkins/plugins/monitoring/MonitorPortlet.java
- src/main/resources/portlet/portlet.jelly
> expand the interface documentation

- README.md
- src/main/java/io/jenkins/plugins/monitoring/ExamplePortlet.java
- src/main/java/io/jenkins/plugins/monitoring/MonitorConfigurationProperty.java
- src/main/java/io/jenkins/plugins/monitoring/MonitorPortlet.java
- src/main/java/io/jenkins/plugins/monitoring/MonitoringDefaultActionFactory.java
- src/main/webapp/css/pull-request-monitoring.css
- src/main/webapp/js/pull-request-monitoring.js
- src/test/java/io/jenkins/plugins/monitoring/MonitorTest.java
> fix codingstyle issues (codacy)

- README.md
- etc/Jenkinsfile.custom
- etc/Jenkinsfile.default
- src/main/java/io/jenkins/plugins/monitoring/ExamplePortlet.java
- src/main/java/io/jenkins/plugins/monitoring/MonitorPortlet.java
- src/main/resources/modals/add-portlet.jelly
> change monitor API for icon url - add default icon if no one is provided

- README.md
- src/main/java/io/jenkins/plugins/monitoring/MonitorPortlet.java
> remove default id implementation from portlet API

- README.md
> fix misleading description in README.md

- src/main/resources/io/jenkins/plugins/monitoring/MonitoringDefaultAction/index.jelly
> fix missing jquery3 adjunct with bootstrap5

- pom.xml
- src/main/resources/alerts/warning.jelly
- src/main/resources/io/jenkins/plugins/monitoring/MonitoringDefaultAction/index.jelly
- src/main/resources/modals/add-portlet.jelly
- src/main/resources/modals/config.jelly
> Bump select2-api from 4.0.13-3 to 4.0.13-4

- src/main/java/io/jenkins/plugins/monitoring/Monitor.java
- src/test/java/io/jenkins/plugins/monitoring/MonitorTest.java
> improved logging

- src/main/java/io/jenkins/plugins/monitoring/MonitoringWorkflowJobActionFactory.java
> if job has no builds, no action will be added (NullPointer fix)

- src/main/java/io/jenkins/plugins/monitoring/MonitoringDefaultAction.java
> set default configuration in getTarget() of StaplerProxy

- src/main/java/io/jenkins/plugins/monitoring/MonitoringDefaultAction.java
- src/main/java/io/jenkins/plugins/monitoring/MonitoringMultibranchProjectAction.java
- src/main/java/io/jenkins/plugins/monitoring/MonitoringWorkflowJobAction.java
> remove stapler proxy for project and job action

- src/main/webapp/css/pull-request-monitoring.css
> change portlet title size from 9px to 12px

- src/main/resources/modals/add-portlet.properties
> unified dashboard naming (portlet instead of plugin)

- pom.xml
- src/main/java/io/jenkins/plugins/monitoring/MonitoringDefaultAction.java
- src/main/resources/alerts/warning.jelly
- src/main/resources/io/jenkins/plugins/monitoring/MonitoringDefaultAction/index.jelly
- src/main/resources/io/jenkins/plugins/monitoring/MonitoringDefaultAction/sidepanel.jelly
- src/main/resources/metadata/metadata.jelly
> add pull request metadata (name, description, contributor, source, target) to dashboard

- README.md
> add git-forensics-api plugin hint for reference build

- README.md
- pom.xml
- src/main/java/io/jenkins/plugins/monitoring/DemoPortlet.java
- src/main/java/io/jenkins/plugins/monitoring/Monitor.java
- src/main/java/io/jenkins/plugins/monitoring/MonitorConfigurationProperty.java
- src/main/java/io/jenkins/plugins/monitoring/MonitoringCustomAction.java
- src/main/java/io/jenkins/plugins/monitoring/MonitoringDefaultAction.java
- src/main/java/io/jenkins/plugins/monitoring/MonitoringDefaultActionFactory.java
- src/main/java/io/jenkins/plugins/monitoring/MonitoringMultibranchProjectAction.java
- src/main/java/io/jenkins/plugins/monitoring/MonitoringMultibranchProjectActionFactory.java
- src/main/java/io/jenkins/plugins/monitoring/MonitoringWorkflowJobAction.java
- src/main/java/io/jenkins/plugins/monitoring/MonitoringWorkflowJobActionFactory.java
- src/test/java/io/jenkins/plugins/monitoring/MonitorTest.java
> intergate analysis-pom project, pom clenaup

- src/main/java/io/jenkins/plugins/monitoring/Monitor.java
- src/main/java/io/jenkins/plugins/monitoring/MonitorConfigurationProperty.java
- src/main/java/io/jenkins/plugins/monitoring/MonitoringDefaultAction.java
- src/main/java/io/jenkins/plugins/monitoring/MonitoringMultibranchProjectAction.java
- src/main/java/io/jenkins/plugins/monitoring/MonitoringWorkflowJobAction.java
- src/main/resources/io/jenkins/plugins/monitoring/Messages.properties
> outsourced static labels to Messages.properties

- pom.xml
- src/main/java/io/jenkins/plugins/monitoring/MonitoringDefaultAction.java
> add markdown to html parser for pull request description

- src/main/java/io/jenkins/plugins/monitoring/Monitor.java
- src/main/java/io/jenkins/plugins/monitoring/MonitorPortlet.java
- src/main/java/io/jenkins/plugins/monitoring/MonitoringDefaultActionFactory.java
- src/main/java/io/jenkins/plugins/monitoring/MonitoringMultibranchProjectAction.java
- src/main/java/io/jenkins/plugins/monitoring/MonitoringWorkflowJobActionFactory.java
- src/main/java/io/jenkins/plugins/monitoring/util/PullRequestFinder.java
> wrap pull request validation into utility class

- src/main/java/io/jenkins/plugins/monitoring/MonitoringDefaultActionFactory.java
- src/main/resources/modals/add-portlet.jelly
> factory is only added to dropdown list if its portlets are not empty

- README.md
- src/main/java/io/jenkins/plugins/monitoring/MonitorPortletFactory.java
> fix broken links after code-coverage and warnings-ng portlets are merged

- src/main/java/io/jenkins/plugins/monitoring/util/PullRequestFinder.java
Add null check for BranchProperty.
> fix npe for unsupported projects

- .github/auto_assign.yml
- .github/workflows/assign-pr.yml
> add pr auto assignment

- pom.xml
Libraries need to be set to fixed versions until Bootstrap 5 has been added to the BOM.
> Update dependencies of UI libraries to latest versions

- src/main/resources/io/jenkins/plugins/monitoring/MonitoringMultibranchProjectAction/index.jelly
Fix broken sim link in pr cards.
> fix broken scm link in pr overview cards

- .github/dependabot.yml
Bump open pull request limit for dependabot from 5 to 10.
> bump open pull request limit for dependabot from 5 to 10

- src/main/java/io/jenkins/plugins/monitoring/Monitor.java
- src/main/java/io/jenkins/plugins/monitoring/MonitorConfigurationProperty.java
- src/main/resources/io/jenkins/plugins/monitoring/Messages.properties
Fixes some issues and flaws from code review.
> Fixes issues and flaws from code review

- README.md
- src/main/java/io/jenkins/plugins/monitoring/Monitor.java
- src/main/java/io/jenkins/plugins/monitoring/MonitorConfigurationProperty.java
- src/main/java/io/jenkins/plugins/monitoring/MonitorPortlet.java
- src/main/java/io/jenkins/plugins/monitoring/MonitoringDefaultAction.java
- src/main/java/io/jenkins/plugins/monitoring/MonitoringDefaultActionFactory.java
- src/main/java/io/jenkins/plugins/monitoring/MonitoringMultibranchProjectAction.java
- src/main/java/io/jenkins/plugins/monitoring/MonitoringWorkflowJobAction.java
- src/main/java/io/jenkins/plugins/monitoring/MonitoringWorkflowJobActionFactory.java
- src/main/java/io/jenkins/plugins/monitoring/util/PortletUtils.java
- src/main/java/io/jenkins/plugins/monitoring/util/PullRequestUtils.java
- src/main/webapp/js/pull-request-monitoring.js
> fix codacy issues

- pom.xml
> remove j2html dependency

- pom.xml
> remove io.jenkins.plugins.echarts-api as dependency management

- pom.xml
> bum echarts-api from 5.1.2-1 to 5.3.3-1

- pom.xml
- src/main/java/io/jenkins/plugins/monitoring/MonitoringDefaultAction.java
> switch jenkins baseline to 2.332.x
